# List of dependencies of the project

[versions]
prepared = "1.5.1"         # https://gitlab.com/opensavvy/groundwork/prepared/-/releases

[plugins]

[libraries]
prepared-kotest = { module = "dev.opensavvy.prepared:runner-kotest", version.ref = "prepared" }

[bundles]
